### PR TITLE
feat: Add rag url knowledge examples

### PR DESCRIPTION
**Pull request by fangyinc**
Add rag url knowledge examples.

To test the current dbgpts, you need to rely on the code of https://github.com/eosphoros-ai/DB-GPT/pull/1341
See `workflow/rag-save-url-to-vstore/README.md` and `workflow/rag-url-knowledge-example/README.md`

### CODE REVIEW

**Comment by dexuandai** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已收到您的来件，会尽快给您回复。

**Review by yhjun1026 — APPROVED** [review]
r+

**Review by Aries-ckt — APPROVED** [review]
r+

**Review by yhjun1026 — COMMENTED** [review]
r+

**Pull request merged**
